agent:
  x: 0
  y: 0
  c: 0
  communication_threshold: 0
  v_max: 1.5
  a_max: 0.5
  damp: 10.0
  nest_radius: 2
  kappa: 8.0
  sigma: 0.1
  theta: 0.5
  sensing_radius: 1
  load_state: False
  communication_threshold_decay: 0.9
  exploration_buffer_radius: 2.0
simulator:
  simulation_length: 1000
  proportion_explorers: 0.3
  exploration_radius: 2.5
  exploration_period: 1000
  num_agents: 20
  forget_frequency: 5
  num_lost_agents: 2
  radius_decoys: 6
  
